### ISSUE TITLE
scssを導入したいがエラーが発生する

### ISSUE THREAD

**Issue by yogi1116** [yogi1116/crazy_man#15]
- 質問内容・実現したいこと
お疲れ様です。  
Rails 7.1.1にてscssを導入するためのdartsass-railsのインストール手順にて②のコマンドを実行しようとしたところ
エラーが発生しました。
①./bin/bundle add dartsass-rails
② ./bin/rails dartsass:install
- 現状発生している問題・エラーメッセージ
```
% ./bin/rails dartsass:install
bin/rails aborted!
LoadError: cannot load such file -- sassc-rails (LoadError)
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Users/yogitsubasa/workspace/crazy_challenge_record/config/application.rb:19:in `<main>'
/Users/yogitsubasa/workspace/crazy_challenge_record/Rakefile:4:in `require_relative'
/Users/yogitsubasa/workspace/crazy_challenge_record/Rakefile:4:in `<main>'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
./bin/rails:4:in `<main>'

Caused by:
LoadError: cannot load such file -- dartsass-sprockets (LoadError)
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Users/yogitsubasa/workspace/crazy_challenge_record/config/application.rb:19:in `<main>'
/Users/yogitsubasa/workspace/crazy_challenge_record/Rakefile:4:in `require_relative'
/Users/yogitsubasa/workspace/crazy_challenge_record/Rakefile:4:in `<main>'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
./bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```
- どの処理までうまく動いているのか
`
% ./bin/bundle add dartsass-rails
`
上記のコマンドではエラーにならずgemfileにdartsass-railsが反映されました
```
gem "dartsass-rails", "~> 0.5.0"
```
- エラーから考えられる原因および試したこと
エラーから考えられる原因として、sassc-railsとdartsass-sprockets見つからないと言われてるが
どちらも現在は非推奨のため、それらを誘導しようとしてる古い設定がgemfileやconfig/application.rbなどに
記載されてるのではと思われたが、該当箇所がgemfileのgem "sprockets-rails"のみだったので、
コメントアウトしたが解決できませんでした。

**Comment by kenchasonakai** [comment]
まずはdartsass-railsのissueに同じようなエラーが出ている人がいないか、またGoogleで同じようなエラーの解決方法がないか調べてみていただけますでしょうか？

**Comment by yogi1116** [comment]
railsサーバーを起動した際も似たようなエラーが発生してました。
```
rails s                   
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- sassc-rails (LoadError)
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.3.2/lib/bootstrap/engine.rb:7:in `rescue in <main>'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.3.2/lib/bootstrap/engine.rb:4:in `<main>'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.3.2/lib/bootstrap.rb:61:in `register_rails_engine'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.3.2/lib/bootstrap.rb:11:in `load!'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.3.2/lib/bootstrap.rb:75:in `<main>'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `each'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `block in require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `each'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler.rb:187:in `require'
        from /Users/yogitsubasa/workspace/crazy_challenge_record/config/application.rb:19:in `<main>'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/server/server_command.rb:139:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/server/server_command.rb:136:in `perform'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/base.rb:178:in `invoke_command'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/base.rb:73:in `perform'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:71:in `block in invoke'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:149:in `with_argv'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:69:in `invoke'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands.rb:18:in `<main>'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
<internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- dartsass-sprockets (LoadError)
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.3.2/lib/bootstrap/engine.rb:5:in `<main>'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.3.2/lib/bootstrap.rb:61:in `register_rails_engine'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.3.2/lib/bootstrap.rb:11:in `load!'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.3.2/lib/bootstrap.rb:75:in `<main>'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `each'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `block in require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `each'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.13/lib/bundler.rb:187:in `require'
        from /Users/yogitsubasa/workspace/crazy_challenge_record/config/application.rb:19:in `<main>'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/server/server_command.rb:139:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/server/server_command.rb:136:in `perform'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/base.rb:178:in `invoke_command'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/base.rb:73:in `perform'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:71:in `block in invoke'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:149:in `with_argv'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:69:in `invoke'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands.rb:18:in `<main>'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
```
エラー内容からsassc-railsやsprocketsを探しているようなので、下記のサイトにあるように
https://qiita.com/naga091/items/715cd48d8d268b307c9b
rails7系で非推奨となっている`gem 'sass-rails'`をgemfileに追加後、再度railsサーバーを起動したところ
上記のようなエラーは発生せず無事起動できました。（`gem "sprockets-rails"`は元から記載がありました）

7系においてscssの導入をするにあたり、sass-railsやsprockets-railsでの導入は良くないのでしょうか？

**Comment by kenchasonakai** [comment]
sass-railsは一応非推奨なので使わない方が無難かなと思います

7.1からはrails newのオプションでsassを選択するとdartsassが入るようになったようです
https://techracho.bpsinc.jp/hachi8833/2023_09_14/122975

**Comment by yogi1116** [comment]
色々な操作を行いファイルがめちゃめちゃになってるので、git reset --hardでgemを導入する前に戻す。
再度dartsass-railsをインストール。
`$ ./bin/bundle add dartsass-rails`
下記のコマンドで毎度エラーを起こしてたが解消された。
```
$ ./bin/rails dartsass:install
       apply  /Users/yogitsubasa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/dartsass-rails-0.5.0/lib/install/dartsass.rb
  Build into app/assets/builds
      create    app/assets/builds
      create    app/assets/builds/.keep
      append    app/assets/config/manifest.js
  Stop linking stylesheets automatically
        gsub    app/assets/config/manifest.js
      append    .gitignore
  Add default app/assets/stylesheets/application.scss
      create    app/assets/stylesheets/application.scss
  Add default Procfile.dev
      create    Procfile.dev
  Ensure foreman is installed
         run    gem install foreman from "."
Successfully installed foreman-0.87.2
Parsing documentation for foreman-0.87.2
Done installing documentation for foreman after 0 seconds
1 gem installed
  Add bin/dev to start foreman
      create    bin/dev
  Compile initial Dart Sass build
         run    rails dartsass:build from "."
         run  bundle install
Using rake 13.1.0
Using base64 0.2.0
Using bigdecimal 3.1.4
Using concurrent-ruby 1.2.2
Using connection_pool 2.4.1

省略

Bundle complete! 20 Gemfile dependencies, 101 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle lock --add-platform=x86_64-linux
Writing lockfile to /Users/yogitsubasa/workspace/crazy_challenge_record/Gemfile.lock
         run  bundle lock --add-platform=aarch64-linux
Writing lockfile to /Users/yogitsubasa/workspace/crazy_challenge_record/Gemfile.lock
```

**Comment by yogi1116** [comment]
`rails s`コマンドにてrailsサーバーを起動するとhtmlは反映されてるが、cssは反映されていない。
上記のインストールコマンド`./bin/rails dartsass:install`にてdartsass-railsをインストールした際に
app/assets/stylesheets/application.scssが自動で作成されてるので、top.scssを読み込めるように`@user 'top';`を記載
さらに`rails s`コマンドではなく`bin/dev`コマンドがdartsass-railsをインストールすることで使えるようになったので
そのコマンドにてrailsサーバーを立ち上げるとcssも反映されるようになった。
